[tool.poetry]
name = "fava-envelope"
version = "0.1.0"
description = ""
authors = ["Brian Ryall <brianryall@fastmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
fava = "^1.14"
pandas = "^1.0.3"
python-language-server = "^0.31.9"
flake8 = "^3.7.9"
pydocstyle = "^5.0.2"
black = "^19.10b0"

[tool.poetry.dev-dependencies]
ipdb = "^0.13.2"
python-language-server = "^0.31.9"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
